services:
  
  postgres-db:
      image: postgres

      restart: always
      volumes:
        - ./data/user-db:/var/lib/postgresql/data
      ports:
        - 5432:5432
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080